[workspace]
resolver = "3"
members = ["crates/*", "examples/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
common = { path = "crates/common" }
rstest = "0.26.1"
tokio = { version = "1.48.0", features = ["full"] }
zenoh = "1.7.2"
