name: zenoh-examples/key-expressions

x-service: &service
  build: &service-build
    context: ../..
    dockerfile: containers/rust-crate-bin/Containerfile
    args: &service-build-args
      CRATE_PATH: examples/1-key-expressions

services:
  pub:
    <<: *service
    build:
      <<: *service-build
      args:
        <<: *service-build-args
        BIN_NAME: pub

  simple:
    <<: *service
    build:
      <<: *service-build
      args:
        <<: *service-build-args
        BIN_NAME: simple
