name: zenoh-examples/hello-zenoh-pub-sub
services:
  pub:
    build:
      context: ../..
      dockerfile: containers/rust_crate_bin.containerfile
      args:
        CRATE_NAME: hello-zenoh-pub-sub
        BIN_NAME: pub
  sub:
    build:
      context: ../..
      dockerfile: containers/rust_crate_bin.containerfile
      args:
        CRATE_NAME: hello-zenoh-pub-sub
        BIN_NAME: sub
